$('#callback_tr_<%= @callback.id %>').replaceWith('<%= j render 'callback_row', callback: @callback %>')
$('#callback_ran_at_<%= @callback.id %>').html("<%= j callback_ran(@callback) %>")
$('#callback_status_<%= @callback.id %>').html("<%= j callback_status(@callback) %>")
$('#callback_last_match_<%= @callback.id %>').text("<%= j @callback.last_match.to_s %>")
$('#callback_last_command_output_<%= @callback.id %>').text("<%= j @callback.last_command_output.to_s %>")
